### ISSUE TITLE
Source of Methods

### ISSUE THREAD

**Issue by meezaan** [GeniusTS/prayer-times#1]
Al Salaamu Alaykum,

Thank you for the beautifully written library.

Can I please ask what the source of the Fajr and Isha angles is for the Gulf, Kuwait and Qatar methods? I can't, for instance, tie the the computation with the Gulf angles to the Dubai Islamic and Charitable Affairs timings. It is possible that they adjust it for whatever reason, but I would just like to know the sources.

Thank you!

**Comment by aboudeh87** [comment]
Wa alaykom assalam wa rahmatu ALLAH

Actually most of calculation methods configurations is taken from [Islamic finder](https://www.islamicfinder.org/) website and also from other applications and libraries like [batoulapps/Adhan](https://github.com/batoulapps/Adhan) and [prayer-now](http://www.prayer-now.com/calculations.html).

If you find any wrong angles please let me know :)

**Comment by meezaan** [comment]
Tesekkur for the prompt response. Thank you, that helps. I can see in https://github.com/batoulapps/Adhan that the there are always manual adjustments taken into account, which is why computed timings will not match timings published locally in the UAE, for instance.

That helps, thank you. I was just updating aladhan.com with more methods, so I wanted to be sure it is is, in fact, the manual 'tuning' of timings that makes them different.
