### ISSUE TITLE
is this still accurate?

### ISSUE THREAD

**Issue by eaponiente** [GeniusTS/prayer-times#4]
I tried installing this plugin and I got the wrong calculations for the prayer time with coordinates of 0,0

**Comment by aboudeh87** [comment]
The calculation depends on the angles of Fajr and ishaa, you can try another method of calculation.

**Comment by vignes111** [comment]
I GOT ERROR..HOW TO RUN THIS PLUGIN...HOW TO USE IT....GIVE SOME SOLUTION FOR THIS......

**Comment by aboudeh87** [comment]
@vignes111  What is the error?!!! how you are using it?!!
